#!/usr/bin/env bash
# This is a Bash script that pings an IP address specified as a command-line argument
 if [ "$#" -eq 1 ]
    then
        ping -c 5 "$1"
    else
        echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    fi
